services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stock-trading
    ports:
      - "27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: