services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stock-trading
    ports:
      - "27017"
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data:
  redis-data: