services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stock-trading
    ports:
      - "27017:27017"
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data:
  redis-data: