name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SOURCE: "./"  # Change this to specify the source directory of your build artifacts
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: "/home/ec2-user/auto-trade"

      - name: Move WAR to Tomcat and re-start Tomcat
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            WAR_FILE="/home/ec2-user/auto-trade/target/stock-trading.war"
            TOMCAT_WEBAPP_DIR="/opt/tomcat/apache-tomcat-9.0.89/webapps"
            TOMCAT_BIN_DIR="/opt/tomcat/apache-tomcat-9.0.89/bin"

            # Stop Tomcat
            sudo systemctl stop tomcat
            
            # Move the WAR file to Tomcat's webapps directory
            sudo mv $WAR_FILE $TOMCAT_WEBAPP_DIR
            
            # Start Tomcat
            sudo systemctl start tomcat
            
            # Optional: Check Tomcat status
            sudo systemctl status tomcat
